<a href="https://colab.research.google.com/github/TakuyaKawachi/gazoubunrui/blob/master/%E5%AD%A6%E7%BF%92%26%E8%A9%A6%E8%A1%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import sys
sys.path.append('/content/drive/My Drive/gazoubunrui/')

import ic_module as ic
import importlib
importlib.reload(ic)

# 関数実行
ic.Learning(tsnum=30, nb_epoch=50, batch_size=8, learn_schedule=0.9)

>> 学習サンプル数 :  (142, 32, 32, 3)
>> 学習開始
Epoch 1/50
6/7 [========================>.....] - ETA: 0s - loss: 0.8704 - accuracy: 0.7083
Epoch 00001: val_loss improved from inf to 1.47206, saving model to best.hdf5
7/7 [==============================] - 1s 99ms/step - loss: 0.9155 - accuracy: 0.6863 - val_loss: 1.4721 - val_accuracy: 0.3297
Epoch 2/50
6/7 [========================>.....] - ETA: 0s - loss: 0.6765 - accuracy: 0.7292
Epoch 00002: val_loss improved from 1.47206 to 1.24111, saving model to best.hdf5
7/7 [==============================] - 1s 75ms/step - loss: 0.6882 - accuracy: 0.7059 - val_loss: 1.2411 - val_accuracy: 0.3297
Epoch 3/50
6/7 [========================>.....] - ETA: 0s - loss: 0.5988 - accuracy: 0.7708
Epoch 00003: val_loss did not improve from 1.24111
7/7 [==============================] - 0s 67ms/step - loss: 0.6131 - accuracy: 0.7647 - val_loss: 1.6154 - val_accuracy: 0.3297
Epoch 4/50
6/7 [========================>.....] - ETA: 0s - loss: 0.6010 - accuracy: 0.750

In [12]:
import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazoubunrui/face/ikutaerika/image_0.jpg
>> 計算結果↓
[[9.2586905e-01 7.4085504e-02 4.5450794e-05]]
>> この画像は「齋藤飛鳥」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazoubunrui/face/ikutaerika/image_24.jpg
>> 計算結果↓
[[9.2572880e-01 7.4260764e-02 1.0442324e-05]]
>> この画像は「齋藤飛鳥」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazoubunrui/face/ikutaerika/image_26.jpg
>> 計算結果↓
[[0.8523666  0.14666344 0.0009699 ]]
>> この画像は「齋藤飛鳥」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazoubunrui/face/ikutaerika/image_27.jpg
>> 計算結果↓
[[0.7786526  0.2198763  0.00147112]]
>> この画像は「齋藤飛鳥」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazoubunrui/face/ikutaerika/image_46.jpg
>> 計算結果↓
[[0.45808262 0.5004678  0.04144954]]
>> この画像は「白石麻衣」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/gazoubunrui/face/ikutaerika/image_47.jpg
>> 計算結果↓
[[0.5924414  0.38503754 0.0225211 ]]
>> この画像は「齋藤飛鳥」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/driv